version: '3.8'

services:
  vollmed-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/vollmed_api
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=121021
      - API_SECURITY_TOKEN_SECRET=12345678
    depends_on:
      - mysql-db
    restart: on-failure

  mysql-db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=vollmed_api
      - MYSQL_ROOT_PASSWORD=121021
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always

volumes:
  db_data: